version: '3'

services:
  seed_docker_flask_json_img:
    restart: unless-stopped
    build: .
    container_name: seed_docker_flask_json
    volumes:
      - './src:/src'
    ports:
      - '5000:5000'
